name: Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '*.md'
      - 'docs/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      fail-fast: true
      matrix:
        php: [8.3, 8.4, 8.5]
        laravel: [12.*, 13.*]
        stability: [prefer-stable]
        include:
          - laravel: 12.*
            testbench: 10.*
          - laravel: 13.*
            testbench: 11.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: pcov

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/pest --coverage --coverage-clover build/logs/clover.xml --coverage-text=build/coverage.txt

      - name: Format coverage report
        if: matrix.php == '8.4' && matrix.laravel == '13.*' && matrix.stability == 'prefer-stable'
        run: |
          mkdir -p build
          echo "### Test Coverage Summary" > build/coverage_summary.md
          echo "" >> build/coverage_summary.md
          awk '
            /Summary:/ { flag = 1; next }
            flag && /^[[:space:]]*$/ { flag = 0; exit }
            flag { print $0 }
          ' build/coverage.txt >> build/coverage_summary.md
          
          cat build/coverage_summary.md >> $GITHUB_STEP_SUMMARY

      - name: Report Coverage
        if: matrix.php == '8.4' && matrix.laravel == '13.*' && matrix.stability == 'prefer-stable'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: coverage
          path: build/coverage_summary.md